import { Container, GlowBackground, PTYTBox } from "@components";

import tokenisation_1 from "@assets/guide/tokenisation/tokenisation_1.png";
import tokenisation_2 from "@assets/guide/tokenisation/tokenisation_2.png";
import PTYT_1 from "@assets/guide/tokenisation/PTYT_1.png";
import PTYT_2 from "@assets/guide/tokenisation/PTYT_2.png";
import PTYT_3 from "@assets/guide/tokenisation/PTYT_3.png";
import PTYT_4 from "@assets/guide/tokenisation/PTYT_4.png";
import character from "@assets/guide/character.png";


const YieldTokenisation = () => {
  return (
    <Container className="relative" background="bg-black">

      <div className="relative">
        <GlowBackground />
      </div>

      <h1 className="text-4xl font-saira items-center text-center text-white mt-5 mb-10">
        Stage 2: Yield Tokenisation
      </h1>

      <div className="flex flex-col gap-5 px-5 py-5 mb-20 bg-dark-transparent rounded-2xl border border-white/20">
        <Container>
          <p className="text-gray-300 leading-relaxed mb-10">
            When you stake <span className="font-bold text-white">STT</span> in the vault, you receive 
            <span className="font-bold text-white"> stSTT</span>, which naturally earns yield over time. 
            For example, staking <span className="font-bold text-white">100 STT</span> in Somnield's Vault
            for six months will result in growth as the 
            <span className="font-bold text-white"> exchange rate</span> steadily increases, reflecting 
            the accumulated yield.
          </p>

          <div className="flex justify-center mb-20">
            <img src={tokenisation_1} className="w-4/5 rounded-lg shadow-lg" />
          </div>

          <p className="text-gray-300 leading-relaxed mb-10">
            With <span className="font-bold text-white">Somnield</span>, your 
            <span className="font-bold text-white"> stSTT</span> can be split into two parts: 
            <span className="font-bold" style={{ color: '#1BDEBF' }}> Principal Tokens (PT)</span> and 
            <span className="font-bold" style={{ color: '#78B4FB' }}> Yield Tokens (YT)</span>. This separation allows you 
            to trade or manage your exposure to principal and yield independently, opening up new 
            strategies for yield optimization.
          </p>

          <div className="flex justify-center mb-20">
            <img src={tokenisation_2} className="w-4/5 rounded-lg shadow-lg" />
          </div>

          {/* PT and YT benefit */}
          <div className="flex flex-col md:flex-row gap-10 mb-20">
            <div className="flex-1">
              <p className="text-gray-300 leading-relaxed">
                Holding <span className="font-bold" style={{ color: '#1BDEBF' }}>Principal Tokens (PT)</span> gives you the right to 
                reclaim your original deposit once the maturity date arrives. For example, after a 3-month term, 
                <span className="font-bold" style={{ color: '#1BDEBF' }}> PT </span> holders can redeem the exact principal amount they started with.
              </p>
            </div>

            {/* Divider for desktop */}
            <div className="hidden md:block w-px bg-white/30"></div>

            <div className="flex-1">
              <p className="text-gray-300 leading-relaxed">
                Meanwhile, <span className="font-bold" style={{ color: '#78B4FB' }}>Yield Tokens (YT)</span> grant access to the ongoing 
                yield generated by the staked asset during the same period. Following this way, <span className="font-bold" style={{ color: '#78B4FB' }}>YT </span> holders benefit from the 
                continuous interest flow up until maturity, separate from the principal.
              </p>
            </div>
          </div>

          {/* Note block */}
          <div className="flex gap-5 mt-10">
            <div className="flex justify-center">
              <img src={character} className="max-w-[80px] max-h-[80px] rounded-full border-2 border-white/30 object-cover"/>
            </div>

            <p className="text-amber-400 leading-relaxed font-semibold">
              Unlike DAI or stETH, which follow a rebasing model where the token amount changes over time, 
              stSTT uses an interest-bearing model. This means the amount stays the same, but its value grows internally. 
              As a result, withdrawals return STT, the non-yielding base asset, instead of the yield-bearing token itself.
            </p>

          </div>
        </Container>
      </div>

      {/* What can you with PT and YT? */}
      <div className="flex flex-col gap-5 px-5 py-5 mb-20 bg-dark-transparent rounded-2xl border border-white/20">
        <Container>
          <h2 className="text-3xl font-saira ">
            What can you do with PT and YT ?
          </h2>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mt-10">
            <PTYTBox 
              index={1} 
              title="Before maturity" 
              description="From each underlying asset, you can generate 1 PT and 1 YT." 
              src={PTYT_1} 
            />
            <PTYTBox 
              index={2} 
              title="Before maturity" 
              description="Combine 1 PT with 1 YT to exchange back into the underlying asset." 
              src={PTYT_2} 
            />
            <PTYTBox 
              index={3} 
              title="Before maturity" 
              description="YT owners are entitled to continuously collect the yield as it accrues." 
              src={PTYT_3} 
            />
            <PTYTBox 
              index={4} 
              title="After maturity" 
              description="PT alone can be swapped for the original asset at a 1:1 rate." 
              src={PTYT_4} 
            />
          </div>
        </Container>
      </div>
    </Container>
  );
};

export default YieldTokenisation;
