import { Container, GlowBackground } from "@components";

import YT_1 from "@assets/guide/YT/YT_1.png";
import YT_2 from "@assets/guide/YT/YT_2.png";

const YTStrategy = () => {
  return (
    <Container className="relative" background="bg-black">

      <div className="relative">
        <GlowBackground />
      </div>

      <h1 className="text-4xl font-saira items-center text-center text-white mt-5 mb-10">
        Stage 4: Longing Yield –{" "}
        <span className="font-bold" style={{ color: '#78B4FB' }}>YT</span> Trade
      </h1>

      {/* Intro section */}
      <div className="flex flex-col gap-5 px-5 py-5 mb-20 bg-dark-transparent rounded-2xl border border-white/20">
        <Container>
          <p className="text-gray-300 leading-relaxed mb-10">
            <span className="font-bold" style={{ color: '#78B4FB' }}>Yield Tokens (YT)</span> 
            {" "}are traded on the{" "}
            <span className="font-bold text-white">Somnield Market</span> in the same pool as Principal Tokens (PT). 
            Buying <span className="font-bold" style={{ color: '#78B4FB' }}>YT</span> means you are 
            effectively{" "}
            <span className="font-bold text-white">longing yield</span>: you pay upfront to receive 
            the future yield of an underlying asset until maturity.
          </p>

          <div className="flex justify-center mb-20">
            <img src={YT_1} className="w-4/5 rounded-lg shadow-lg" />
          </div>

          <p className="text-gray-300 leading-relaxed mb-5">
            For example, suppose{" "}
            <span className="font-bold" style={{ color: '#78B4FB' }}>1 YT-stSTT </span> 
            is trading at{" "}
            <span className="font-bold text-white">0.04 STT</span>, with a maturity in{" "}
            <span className="font-bold text-white">1 year</span>. 
            Holding it entitles you to the yield from{" "}
            <span className="font-bold text-white">1 stSTT</span> until maturity.
          </p>

          <p className="text-gray-300 leading-relaxed mb-10">
            If you believe that{" "}
            <span className="font-bold text-white">1 stSTT</span> will generate more than{" "}
            <span className="font-bold text-white">0.04 STT</span> in yield during that year 
            (equivalent to a 4% APY), buying{" "}
            <span className="font-bold" style={{ color: '#78B4FB' }}>YT</span> is profitable. 
            You earn the difference between the{" "}
            <span className="font-bold text-white">future yield</span> and the{" "}
            <span className="font-bold text-white">cost of YT</span>.
          </p>

          <div className="flex justify-center mb-10">
            <img src={YT_2} className="w-4/5 rounded-lg shadow-lg" />
          </div>

          <p className="text-gray-300 leading-relaxed mb-5">
            In simple terms, this is what a <span className="font-bold" style={{ color: '#78B4FB' }}>YT</span> trade looks like:
          </p>

          <div className="space-y-3 mb-10">
            <div className="bg-[#152D35] rounded-xl p-4 border border-white/10 text-[#78B4FB] font-bold">
              Buy and hold <span className="font-bold" style={{ color: '#78B4FB' }}>YT</span> → Long yield until maturity
            </div>
            <div className="bg-[#152D35] rounded-xl p-4 border border-white/10 text-[#78B4FB] font-bold">
              Profits = Future yield – YT cost
            </div>
          </div>

        </Container>
      </div>

      {/* When should you buy YT? */}
      <div className="flex flex-col gap-5 px-5 py-5 mb-20 bg-dark-transparent rounded-2xl border border-white/20">
        <Container>
          <div className="relative">
            <GlowBackground />
          </div>

          <h2 className="text-3xl font-saira mb-10">
            When should you buy{" "}
            <span className="font-bold" style={{ color: '#78B4FB' }}>YT</span>?
          </h2>

          <p className="text-gray-300 leading-relaxed mb-5">
            The simplest way to frame{" "}
            <span className="font-bold" style={{ color: '#78B4FB' }}>YT trading</span>{" "}
            is by comparing{" "}
            <span className="font-bold text-white">Implied APY </span> 
            (the APY the market is pricing in) with the{" "}
            <span className="font-bold text-white">Underlying APY </span> 
            (the APY currently being generated by the protocol).
          </p>

          <div className="space-y-3 mb-10">
            <div className="bg-[#152D35] rounded-xl p-4 border border-white/10 text-gray-300 font-bold">
              1. If Implied APY is{" "}
              <span className="text-[#78B4FB]">lower</span> than Underlying APY → 
              Buying <span className="font-bold" style={{ color: '#78B4FB' }}>YT</span> is more likely to be profitable.
            </div>
            <div className="bg-[#152D35] rounded-xl p-4 border border-white/10 text-gray-300 font-bold">
              2. If Implied APY is{" "}
              <span className="text-[#78B4FB]">higher</span> than Underlying APY → 
              Buying <span className="font-bold" style={{ color: '#78B4FB' }}>YT</span> is less likely to be profitable.
            </div>
          </div>

          {/* Pro Tip Box */}
          <div className="bg-[#152D35] text-[#78B4FB] font-bold p-4 rounded-lg mb-10">
            Pro Tip: Use the current Underlying APY as a simple estimate of 
            the future APY. If conditions remain stable, this is a good baseline 
            to decide whether{" "}
            <span className="font-bold" style={{ color: '#78B4FB' }}>YT</span> 
            is underpriced or overpriced.
          </div>
        </Container>
      </div>

    </Container>
  );
};

export default YTStrategy;
